### ISSUE TITLE
Unable to run Medium model

### ISSUE THREAD

**Issue by FrancescoMasaia** [MeetKai/functionary#88]
I've tried to use two A6000 with 48 GB of VRAM each.
The command that i was using was
`python3 server_vllm.py --model "meetkai/functionary-medium-v2.2" --host 0.0.0.0 --tensor-parallel-size 2`

But after downloading everything and loading the first part of the model, it gives the current error.
```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB. GPU 1 has a total capacty of 47.54 GiB of which 215.88 MiB is free. Process 3034125 has 47.32 GiB memory in use. Of the allocated memory 46.89 GiB is allocated by PyTorch, and 9.18 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

I'm not very practical of vllm but it seems that besides the `--tensor-parallel-size 2` command it still loads the model only on the first one, I've also tried to reduce maximum used memory to 95 with `--gpu-memory-utilization 0.95` but it didn't work.

Do you managed to run this model on a machine with that kind of specs or do I need to have a single board with at least 90GB of VRAM to run it?

**Comment by jeffrey-fong** [comment]
Thank you for trying out our models! The functionary-medium-v2.2 model requires a minimum of 2 A100-80GB or 4 A6000s to load and perform inference successfully. We will update this requirement in the README soon.

Alternatively, if you are tight on compute resources, you can try our GGUF model from [here](https://huggingface.co/meetkai/functionary-medium-v2.2-GGUF) using our sample [llama-cpp-python code](https://github.com/MeetKai/functionary?tab=readme-ov-file#llama_cpp-inference). It contains both 4-bit and 8-bit quantized models.

**Comment by FrancescoMasaia** [comment]
Thank you for the response, have you already tried the quantized model? How do they perform relative to the non quantized one?In the next days I’ll try both for sure.Il giorno 13 gen 2024, alle ore 01:17, Jeffrey Fong ***@***.***> ha scritto:﻿
Thank you for trying out our models! The functionary-medium-v2.2 model requires a minimum of 2 A100-80GB or 4 A6000s to load and perform inference successfully. We will update this requirement in the README soon.
Alternatively, if you are tight on compute resources, you can try our GGUF model from here using our sample llama-cpp-python code. It contains both 4-bit and 8-bit quantized models.

**Comment by jeffrey-fong** [comment]
We have only done simple tests with the basic queries and functions just to make sure they work fine and they do indeed work. Feel free to try with more complex queries/tasks!

**Comment by FrancescoMasaia** [comment]
I've done a simple test with 4xA6000 it seemed to work correctly.

Probably with the right prompt strategy i can get similar results to GPT3.5 but right now it doesn't seems to reach the same performance in function calling (especially while correcting the previous request), I'll further investigate in the future.

for example: 
- I want to reserve a table for 9PM
(IT CHECK AVAILABILITY FOR 9PM THROUGHT FUNCTION)
- Sorry we don't have a free table for 9PM but we have one for 9:30PM
- Ok I want that for 9:30PM
(IT STILL CHECK AVAILABILTY FOR 9PM INSTEAD CHANGING IT TO 9:30PM)

**Comment by musabgultekin** [comment]
@FrancescoMasaia 

There was a bug in the transformers library that has just been resolved recently: https://github.com/huggingface/transformers/pull/28256
As we were using the transformers library's loss calculation, the quality degradation on medium model might be related to that.

**Comment by waleking** [comment]
> I've tried to use two A6000 with 48 GB of VRAM each. The command that i was using was `python3 server_vllm.py --model "meetkai/functionary-medium-v2.2" --host 0.0.0.0 --tensor-parallel-size 2`
> 
> But after downloading everything and loading the first part of the model, it gives the current error.
> 
> ```
> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB. GPU 1 has a total capacty of 47.54 GiB of which 215.88 MiB is free. Process 3034125 has 47.32 GiB memory in use. Of the allocated memory 46.89 GiB is allocated by PyTorch, and 9.18 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> ```
> 
> I'm not very practical of vllm but it seems that besides the `--tensor-parallel-size 2` command it still loads the model only on the first one, I've also tried to reduce maximum used memory to 95 with `--gpu-memory-utilization 0.95` but it didn't work.
> 
> Do you managed to run this model on a machine with that kind of specs or do I need to have a single board with at least 90GB of VRAM to run it?

Thanks @FrancescoMasaia, your code works for me. Even when I have 4 A100 (80GB), I still met the error of "Out of memory" without adding `--tensor-parallel-size 2` and `--gpu-memory-utilization 0.95`. But after using yours, medium model can be run.

**Comment by FrancescoMasaia** [comment]
> > I've tried to use two A6000 with 48 GB of VRAM each. The command that i was using was `python3 server_vllm.py --model "meetkai/functionary-medium-v2.2" --host 0.0.0.0 --tensor-parallel-size 2`
> > But after downloading everything and loading the first part of the model, it gives the current error.
> > ```
> > torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB. GPU 1 has a total capacty of 47.54 GiB of which 215.88 MiB is free. Process 3034125 has 47.32 GiB memory in use. Of the allocated memory 46.89 GiB is allocated by PyTorch, and 9.18 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm not very practical of vllm but it seems that besides the `--tensor-parallel-size 2` command it still loads the model only on the first one, I've also tried to reduce maximum used memory to 95 with `--gpu-memory-utilization 0.95` but it didn't work.
> > Do you managed to run this model on a machine with that kind of specs or do I need to have a single board with at least 90GB of VRAM to run it?
> 
> Thanks @FrancescoMasaia, your code works for me. Even when I have 4 A100 (80GB), I still met the error of "Out of memory" without adding `--tensor-parallel-size 2` and `--gpu-memory-utilization 0.95`. But after using yours, medium model can be run.

I've managed to make it work without `--gpu-memory-utilization 0.95` but yeah the problem was related to memory usage, I was thinking that 92 GB was enough but it seems that more memory is needed

**Comment by FrancescoMasaia** [comment]
> @FrancescoMasaia
> 
> There was a bug in the transformers library that has just been resolved recently: [huggingface/transformers#28256](https://github.com/huggingface/transformers/pull/28256) As we were using the transformers library's loss calculation, the quality degradation on medium model might be related to that.



> @FrancescoMasaia
> 
> There was a bug in the transformers library that has just been resolved recently: [huggingface/transformers#28256](https://github.com/huggingface/transformers/pull/28256) As we were using the transformers library's loss calculation, the quality degradation on medium model might be related to that.

So yesterday the bug wasn't fixed yet?

**Comment by KaruroChori** [comment]
It was, merged to main 5 days ago, but it is likely the version your are currently using is not that recent.

**Comment by jeffreymeetkai** [comment]
I will be closing this issue now. Thank you!
